name: GitHub Metrics

on:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: MiraclePlayTeam
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          committer_message: "Update metrics [Skip GitHub Action]"

          # 🔤 언어 통계
          plugin_languages: yes
          plugin_languages_ignored: html,css
          plugin_languages_limit: 8

          # 🔥 활동 통계
          plugin_traffic: yes
          plugin_lines: yes
          plugin_followup: yes

          # 🏆 리포지토리 통계
          plugin_repositories: yes
          plugin_repositories_featured: MiraclePlayTeam/miracle-apex,MiraclePlayTeam/miracle-server,MiraclePlayTeam/miracle-chain-api
